POST http://localhost:3000/user HTTP/1.1
content-type: application/graphql

mutation { 
  createUser(user: {
    name: "a", email: "a1s@qasqssw.qw", password: "sddds"
  }) { 
    id, name, email 
  }
}
###
GET http://localhost:3000/user HTTP/1.1
content-type: application/graphql

{ 
  user {
    name,
    email
  }
}

###
GET http://localhost:3000/user/only-for-admin HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsInNheSI6IkhpISIsInJvbGUiOiJndWVzdCJ9.c61EOIEb1atZawKme7tV1UVbiObIbpwTqWvFKyaoX2M

###
GET http://localhost:3000/user/get-test-token HTTP/1.1
content-type: text/html

###
POST http://localhost:3000/user/check-test-token HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsInNheSI6IkhpISIsInJvbGUiOiJndWVzdCJ9.c61EOIEb1atZawKme7tV1UVbiObIbpwTqWvFKyaoX2M
